### ISSUE TITLE
Add syntax coloring for code snippets

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot-question2answer#5]
Code snippets are shared very often on the website, so it would be really useful to have syntax coloring for at least GDScript, C++, C# and JSON.

The syntax for this could be similar to Github, like:
```
```gdscript
code
```

And have the option to choose language if the block is added with the visual formatting buttons.

**Comment by hiulit** [comment]
[Prism.js](https://prismjs.com/) could be a good choice for syntaxt highlighting.

And it supports GDscript among a lot of other languages :) https://prismjs.com/#supported-languages

I've used it in some projects an it's really easy to set up https://prismjs.com/#basic-usage.

**Comment by Calinou** [comment]
Unfortunately, [Question2Answer is barely maintained anymore](https://github.com/q2a/question2answer), so doing extra development work on top of it may prove difficult. It's still technically feasible though.

**Comment by Zylann** [comment]
It doesn't seem like it has stopped "officially". Otherwise, should we plan to do something about it? Migrating to something else?

**Comment by Calinou** [comment]
@Zylann I don't know exactly. Creating a maintained fork of Question2Answer is probably too much work for a single person (or even 2-3). I see at least two solutions to this:

- Officially recommend Stack Overflow or [gamedev.stackexchange.com](https://gamedev.stackexchange.com) to ask questions. This way, we don't have to maintain a platform ourselves.
- Use the unofficial [Godot forums](https://godotforums.org) instead.

In both cases, we'd keep the Q&A platform available but in a read-only status (so it can still appear in search results).

Also, there's a plugin for syntax highlighting [here](https://github.com/amiyasahu/q2a-syntax-highlighter) but it uses Highlight.js instead of Prism.js. Perhaps we could make it work by installing an unofficial GDScript highlighting definition (since Highlight.js doesn't support it officially).

**Comment by mhilbrunner** [comment]
FWIW, I'm in favor of moving to Stackoverflow or somewhere else and not having to maintain the Q&A :)

**Comment by Zylann** [comment]
My only concern with SO is the apparent lack of visibility. It's not overtly Godot-focused, and you have to use the `godot` tag before anything. It has only 359 questions with `godot` tag (`154` with `gdscript`), while the current QA website has `14,206` and lots of helping people active. (SO doesn't seem to have highlighting for GDScript?)
I'm not familiar with godotforums, but forums are usually a bit different from a Q&A website, more slow paced and less focused on questions/comments. Also, still seems to have way less posts, about 10 times less. But it could work too.
The switch to Godot 4 might sound like a milestone in which to do a change at least (sorry of the  diverging from the original issue^^")

**Comment by dhAlcojor** [comment]
What about getting our own Godot Stack Exchange? It can be done in their [Area 51](https://area51.stackexchange.com/).
![image](https://user-images.githubusercontent.com/567687/128592337-4f9c471c-4962-4fce-afa4-0b8a8cc71d1b.png)

**Comment by Calinou** [comment]
> What about getting our own Godot Stack Exchange? It can be done in their [Area 51](https://area51.stackexchange.com/).

While technically possible, I think the community has settled on the Godot Q&A instead. Not to mention the Stack Exchange website and community got bad press for a few reasons, such as centering the business behind the website at the expense of the community. (Look at the hot posts appearing regularly on Meta Stack Overflow and you'll see :stuck_out_tongue:)

Nonetheless, I just managed to re-add syntax highlighting to the Godot Q&A. You can see it in action by opening any post that has code blocks on the Q&A website :slightly_smiling_face:
